name: Java Snyk Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout Source Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Build Maven Project
      - name: Build Application
        run: mvn clean install

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      #Authenticate Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # - name: verify Snyk Authentication
        #run: snyk whoami

       # SCA Scan
      - name: Run SCA Scan
        run: snyk test 

      #SAST Scan
      - name: Run SAST Scan 
       # run: snyk code test --severity-threshold=high 

      # IaC Scan
      #- name: Run IaC Scan
      #  run: snyk iac test

      # Monitor Project in Snyk 

    

        
